### ISSUE TITLE
Anonymous containers

### ISSUE THREAD

**Issue by roblabla** [roblabla/Protocols#2]
Anonymous containers get their fields written to/read from the parent container. This needs to be implemented on the "readFields" level, so that *every* type that returns an object can have their fields added to the parent. This would be especially useful for switch type. 

Given a naive implementation of "switch" :

```javascript
var x = [{ name: "mySwitch", type: "switch", typeArgs: { field: { name: "inner", type: "struct", typeArgs: { fields: [
  { name: 'one', type: 'int' },
  { name: 'two', type: 'int' }
]}}}}]
```

To access the inner field, we would need to do ```packet.mySwitch.inner.one```. This is suboptimal at best. To avoid this problem, in the current implementation of switch, we copy all the fields of the given container into the body of the switch. However, it'd be nice if this could make automagically. Furthermore, it'd be even better if we could put mySwitch's fields into the parent structure directly, so accessing them would be as easy as ```packet.one```.

**Comment by roblabla** [comment]
container could probably have an "anon" switch easily now. The only problem is, you need to make sure you always return an object for the copy to work. Any other datatype will have to fail.

Example :

```json
["container", [
  { "name": "tag", "type": "int" },
  { "anon": true, "type": ["switch", {
    "compareTo": "this.tag",
    "fields": {
      "0": ["container", [
       { "name": "one", "type": "int" },
       { "name": "two", "type": "Int" },
      ]]
    },
    "default": ["container", []]
  }]}
]]
```

**Comment by rom1504** [comment]
done in nmp
