### ISSUE TITLE
Decouple name from the _readField.

### ISSUE THREAD

**Issue by roblabla** [roblabla/Protocols#7]
A note on typeArgs and fields and stuff : Protocols doesn't define typeArgs at all. Types in protocols come in three different flavors :

- A full object, in which case it looks like { type: "name", someArgs: ..., someOtherArg: ... }
- An array, in which case it is syntax sugar for { type: "struct", fields: the given array }
- A string, which is syntax sugar for { type: "given string" }

The read function takes a buffer+cursor, a type and a context. The name isn't going to be used by the generic _readField anymore. It is currently only used to augment error types. Instead of dealing with that in _readField, it seems smarter to delegate that work to the different containers. As such, name will just be a normal argument for type struct.

This is linked to #2

**Comment by rom1504** [comment]
now solved in https://github.com/PrismarineJS/node-minecraft-protocol/pull/221
